### ISSUE TITLE
로컬에서 문서 작성할때도 GA 페이지뷰 카운트 됩니다

### ISSUE THREAD

**Issue by kgcrom** [tosslab/tosslab.github.io#31]
두가지 방법이 있는데 어떻게 나을까요?
의견을 나눠봐요

```javascript
if (document.location.hostname.search('tosslab.github.io') !== -1) {
  // GA Code
}
```

```javascript
{% if jekyll.environment == 'development' %}
  // Nothing!!
{% else %} 
  // GA Code
{% endif %}
```
[Jekyll different settings](http://david.elbe.me/jekyll/2015/06/08/jekyll-different-settings-production-github-and-development.html)

첫번째는 지금 처럼 진행해도 문제 없지만 도메인이 변경되면(?ㅋㅋ) 이곳도 바꿔 줘야 한다는 점,
두번째는 로컬에서 포스트 작성할때 JEKYLL_ENV=development 이 앞에 추가되어야 한다는 점입니다. (빼먹을경우 지금처럼 GA에 카운트가 되겠죠?)

**Comment by agileup** [comment]
@kgcrom https://github.com/jekyll/jekyll/issues/1219#issuecomment-110395756
직접 테스트해보진 못했지만 위 코멘트 내용으로 봐서는 
```js
{% if jekyll.environment == 'production' %}
  // GA Code
{% endif %}
```
이렇게만 설정해줘도 해결할 수 있을것 같네요 :)

**Comment by kgcrom** [comment]
github pages 에서 설정값이 어떻게 될지 몰라서 두개의 if 문으로 했는데 MK 얘기처럼 하면 되겠네요.
[github-pages stackoverflow](http://stackoverflow.com/questions/34603799/setting-jekyll-environment-for-github-pages)
더 알아봤어야하는데 아쉽...

굿맨 MK

**Comment by agileup** [comment]
#33
