### ISSUE TITLE
'Android 와 Annotation'글 에서 링크가 깨집니다.

### ISSUE THREAD

**Issue by sn0wle0pard** [tosslab/tosslab.github.io#42]
안녕하세요? 항상 좋은글 잘 읽고 있습니다. 다름이 아니라 [이 글](http://tosslab.github.io/android/2015/03/01/02.android-%EC%99%80-annotation.html)에서 목차 링크들이 깨져 있습니다 . 글은 존재하는데 링크가 잘못 걸린것 같습니다 :)

**Comment by agileup** [comment]
#43 깨진 링크 수정되었습니다. 감사합니다.
